# Generated by Django 6.0.5 on 2026-06-01 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('GERENTE', 'Gerente'), ('ALMACENERO', 'Almacenero'), ('VENDEDOR', 'Vendedor')], default='VENDEDOR', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True)),
                ('usa_google', models.BooleanField(default=False)),
                ('mfa_activo', models.BooleanField(default=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
