# Generated by Django 6.0.5 on 2026-06-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='id_usuario_sistema',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ID de usuario en SQL Server'),
        ),
    ]
